name: Fetch and Update Quote

on:
  schedule:
    - cron: '*/5 * * * *'  # This will run every 5 minutes

jobs:
  fetch-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the script
        run: |
          python quote.py  
