name: Update Quote of the Day

on:
  schedule:
    - cron: '0 0 * * *'  # This means the action runs every day at midnight (UTC)
  workflow_dispatch:  # Allow manual triggering of the action

jobs:
  update-quote:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git for GitHub Actions
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
    
    - name: Set up authentication using the GitHub token
      run: |
        git remote set-url origin https://github.com/${{ github.repository }}
        git config --global credential.helper 'store'
        echo "https://${{ secrets.GH_TOKEN }}:@github.com" > ~/.git-credentials

    - name: Update the quote
      run: |
        # Your script to fetch and update the quote here
        echo "Updated quote" > quote.txt
        git add quote.txt
        git commit -m "Update daily quote"
        git push origin main
